### ISSUE TITLE
Typo in GarleanuPanageasModel?

### ISSUE THREAD

**Issue by MaximilianJHuber** [matthieugomez/EconPDEs.jl#1]
I am working through your [GarleanuPanageasModel](https://github.com/matthieugomez/EconPDEs.jl/blob/master/examples/GarleanuPanageas.jl) and I think I found a typo, but I cannot be sure, because I do not know with certainty how your `pA` and `mcA` maps into the [paper](https://www.journals.uchicago.edu/doi/full/10.1086/680996)'s `g^A` and `n^A`. The former is suggested by the definition of `κ`, the latter by the definition of `r`.

Anyway, the denominator of [equation 9](https://www.journals.uchicago.edu/na101/home/literatum/publisher/uchicago/journals/content/jpe/2015/679510/680996/production/images/medium/df11.tif.gif) has the terms concerning `A` with a plus sign and the terms with `B` with a minus sign. This is an error, unless `pAx/pA = - gAx/gA`.

Furthermore, equation A.16 in the [appendix](https://www.journals.uchicago.edu/doi/suppl/10.1086/680996/suppl_file/garleanu.onlineapp.pdf) defines `n^A` which resembles your `mcA` almost perfectly. But, the coefficient in the second line agrees with you definition of `mcA`, only if `γA/(1-γA) = 1`, which is not true.

Is there a documentation that could accompany the example?

**Comment by matthieugomez** [comment]
Good catch. I think it is a typo in the Garleanu Panageas appendix.
Can you try to rederive A.16 from A.14 and tell me whether you obtain their formula vs my formula?

**Comment by MaximilianJHuber** [comment]
You are right. I collected all terms with a `κ` from A.14 and found your expression, not the one in the paper.
How did you know it was a mistake? Again, is there a supporting document you have for your example?

**Comment by matthieugomez** [comment]
Cool, thanks. I’ll upload some notes.

**Comment by matthieugomez** [comment]
Actually just have a look at slides 9 [http://www.matthieugomez.com/teaching.html](here)
