### ISSUE TITLE
Aiyagari Continuous Time eample using EconPDEs

### ISSUE THREAD

**Issue by finmod** [matthieugomez/EconPDEs.jl#12]
The Aiyagari Continuous Time example has not reappeared in the EconPDEs example. AiyagariContinuousTime.jl. 

More generally a current and present value Hamiltonian growth model would be nice.

**Comment by matthieugomez** [comment]
What would you like in AiyagariContinuousTime that is not done in `AchdouHanLasryLionsMoll_OneAsset.jl`?

**Comment by finmod** [comment]
Just a few more lines of docs and references in README of EconPDE and of AiyagariContinuousTime to show where and how the knowledge is consolidated in EconPDE.

**Comment by matthieugomez** [comment]
The Readme now lists the paper
