### ISSUE TITLE
Finite horizon boundary problem 

### ISSUE THREAD

**Issue by azev77** [matthieugomez/EconPDEs.jl#14]
I'm having trouble solving a simple finite horizon bvp. 

A simple example: 
```
V_t + 2*V_x =0
V(0,t) = t
```
The closed form solution is V(x,t) = .5*(2t-x). 
Is there a direct way to solve this using EconPDEs?

**Comment by matthieugomez** [comment]
I don’t think so — it’s more about PDEs that correspond to some kind of backward iterations.

**Comment by azev77** [comment]
Just to be clear, does that mean it currently isn't designed to solve finite horizon problems, boundary value problems, or both?

For example, a deterministic, finite horizon version of the [consumption-saving problem](https://github.com/matthieugomez/EconPDEs.jl/blob/master/examples/ConsumptionProblem/AchdouHanLasryLionsMoll_OneAsset.jl)? with terminal wealth
```
V(w, T) = (w^(1-gamma))/(1-gamma)
```

**Comment by matthieugomez** [comment]
It is not designed to solve any BVP. It can solve finite horizon problems,
as well as infinite horizon problems.
