### ISSUE TITLE
CambpellCochrane.jl

### ISSUE THREAD

**Issue by vr235** [matthieugomez/EconPDEs.jl#17]
Wachter (2005) calibration should have b=0.011, not 0.011*4 as it is right now in the code. It is already annualized; there is no need to multiply it by 4 (Wachter reports already annualized parameters). 
I verified it against published 2005 FRL paper by computing E[r_f]. With b=0.011 it matches the published result.

**Comment by matthieugomez** [comment]
Thanks! Just modified it.

**Comment by vr235** [comment]
Great! I am going through the code line by line since I intend to use it for my research. 
I have one more concern, and here I might be wrong, is:
"Sbar = σ * sqrt(γ / (κs - b / γ))" even correct? 
Formula in the text is "Sbar = σ * sqrt(γ / (1 - κs - b / γ))", however I admit that I might not understand the issue fully. It does not affect the results much (only lambda) since Sbar determines  grid parameters which ultimately do not matter for as long as solution converges. However, it impacts surplus consumption over which P/D is spanned - at this is an important takeaway from the paper. 
Finally, I have some issues with replicating r_m results using this code - if you ever have time please add your version of how to compute it so I can cross-reference. 
When I am finished, I also intend to upload my version of the file - it has line-by-line comments, which should make it more instructive. 
Thanks,
Vitaliy

**Comment by vr235** [comment]
Forget about Sbar = σ * sqrt(γ / (1 - κs - b / γ)) question. I see how variables are redefined now. 
Still , I have two issues remaining: 
1. r_f using the code replicates Wachter (2005) but not CC (1999)
2. Can't replicate r_m
