### ISSUE TITLE
Finite horizon consumption-saving problem

### ISSUE THREAD

**Issue by azev77** [matthieugomez/EconPDEs.jl#19]
How can I use this package to solve a finite horizon [lifecycle model](https://benjaminmoll.com/wp-content/uploads/2020/06/lifecycle.pdf) such as this one by Moll?
His [Matlab code is here](https://benjaminmoll.com/wp-content/uploads/2020/06/lifecycle.m).

**Comment by ptoche** [comment]
There is a Julia translation of Ben Moll's Matlab code to Julia [here](https://github.com/chandlerlester/Radio_Free_Julia/blob/master/Moll_Code/Section03-LifeCycleModel/lifecycle.jl). It does not use `EconPDE.jl`, but can at least get you started.

**Comment by matthieugomez** [comment]
Yes, it is possible, if you add a fourth argument in `pdesolve` ​--- look at https://github.com/matthieugomez/EconPDEs.jl/blob/master/examples/AssetPricing/ArbitrageHoldingCosts.jl for an example.

		The basic idea is that, in this case, the third argument of `pdesolve` should be the value function at terminal time and the fourth should be a vector for times:

		```julia
		m = AchdouHanLasryLionsMollModel()
		distribution = Gamma(2 * m.κy * m.ybar / m.σy^2, m.σy^2 / (2 * m.κy))
		stategrid = OrderedDict(:y => range(quantile(distribution, 0.001), quantile(distribution, 0.999), length = 10), 
		                 			:a =>  range(m.amin, m.amax, length = 100))

		# terminal value of value function
		yend = OrderedDict(:v => zeros((0, 1000)
		# time grid of 20 years
		τs = range(0, stop = 20, step = 1)
		y, result, distance = pdesolve(m, stategrid, yend, τs)
		'''
