### ISSUE TITLE
pdesolve error

### ISSUE THREAD

**Issue by jayhjim88** [matthieugomez/EconPDEs.jl#2]
Hi, thanks for a great package. I am having trouble with running the pdesolve function. In running your example codes, I keep bumping into this error : 

>pdesolve(m, grid, y0)
ERROR: MethodError: no method matching pdesolve(::CampbellCochraneModel, ::Plots.#grid, ::DataStructures.OrderedDict{Symbol,Array{Float64,1}})
Closest candidates are:
  pdesolve(::Any, ::DataStructures.OrderedDict, ::DataStructures.OrderedDict; is_algebraic, kwargs...) at C:\Users\jhji\.julia\v0.6\EconPDEs\src\pdesolve.jl:235
Stacktrace:
 [1] eval(::Module, ::Any) at .\boot.jl:235

Above is case when I run Campbell and Cochrane example, but all others return similar. I am using following packages :

IJulia,DataFrames,Plots,TaylorSeries,QuantEcon,Interpolations,Optim,Roots,Distributions,Combinatorics,DataStructures,BandedMatrices, AiyagariContinuousTime,EconPDEs

Thanks in advance!

**Edit**
I think I figured out the typo in the example. I think you meant to type pdesolve(m, state, y0) in example script.

**Comment by matthieugomez** [comment]
This sounds like a usage issue. Please use this page to only report bugs, not issue you may have using Julia

**Comment by matthieugomez** [comment]
Which example script?

**Comment by matthieugomez** [comment]
I see, thanks. I have just removed the file.
