### ISSUE TITLE
Bug in AchdouHanLasryLionsMoll one asset example

### ISSUE THREAD

**Issue by finmod** [matthieugomez/EconPDEs.jl#21]
In the AchdouHanLasryLionsMoll one asset example, the crucial pdesolve command has disappeared:

m = AchdouHanLasryLionsMollModel()
stategrid = initialize_stategrid(m)
y0 = initialize_y(m, stategrid)
y, result, distance = pdesolve(m, stategrid, y0)

**Comment by matthieugomez** [comment]
Solved. Thanks!

**Comment by finmod** [comment]
The same patch carries over to WangWangYang.
