### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by ijustink** [matthieugomez/EconPDEs.jl#29]
Hello:

I'm very new to Julia and I'm not sure if this is my problem or the code has issue because of the Julia version change or etc.

All of you codes in example folder shows following error.

ERROR: LoadError: syntax: invalid assignment location "; c, r, ρ, σ, a, T"

I removed ';' sign in the function code like this

function (m::ArbitrageHoldingCosts)(state::NamedTuple, y::NamedTuple, τ::Number)
    (c, r, ρ, σ, a, T) = m
    (z) = state
    (F, Fz_up, Fz_down, Fzz) = y

but then Julia shows: 

ERROR: LoadError: MethodError: no method matching iterate

I really want to learn from your code. Could you please help me out with this issue?

**Comment by matthieugomez** [comment]
The code in the example folder requires Julia 1.7. Which version do you
have?

**Comment by ijustink** [comment]
Just installed Julia 1.7.1 version and it works flawlessly. (Previously, I used Julia 1.6.3)

Thank you so much for the quick response and for sharing the code. 

As a Finance PhD student, your code is the most useful resource to learn Julia and theory papers.
