### ISSUE TITLE
More than two states

### ISSUE THREAD

**Issue by greimel** [matthieugomez/EconPDEs.jl#31]
I would like to replace my own HJB solver with this package. In the process I realized that it cannot handle more than two state variables. 

One obvious reason is that the `differentiate` function has methods for one and two states. Did you also assume 2 states in the rest of the package, or would it be enough to provide another method for `differentiate`?

**Comment by matthieugomez** [comment]
Yes I think that a differentiate method with three states would be enough.

**Comment by matthieugomez** [comment]
Done (although three state variables is much slower)
