### ISSUE TITLE
DiTella Model

### ISSUE THREAD

**Issue by ForumWhiner** [matthieugomez/EconPDEs.jl#5]
pdesolve(m, state,y0) returns the error "**MethodError: no method matching norm(::Array{Float64,3},::Float64)**" for DiTella model. I think the problem is that since we have a 3D array in the form of (pA, pB, and p), at some point the FiniteDifferenceScheme tries to calculate norm of this 3D array, which is not acceptable. Any idea how to fix this? Thanks.

**Comment by matthieugomez** [comment]
Try to update NLsolve with Pkg.update(). Does that work?

**Comment by ForumWhiner** [comment]
Thanks for the tip. I updated NLsolve to v1.1.1 but still I am getting the same error. I am using Julia 0.7. I tried using Julia 1.0 but unfortunately there is a problem with using NamedTuples in the latest version (see here: https://github.com/JuliaData/NamedTuples.jl/issues/72).

**Comment by ForumWhiner** [comment]
It works now with your updated codes. Thanks! :)  👍
